PROJECT_PATH=/var/lib/poc_container

# TODO: get from args
container_name='example_container'

IMAGES_PATH=$PROJECT_PATH/overlay
MOUNTPOINTS_PATH=$PROJECT_PATH/mnt
META_PATH=$PROJECT_PATH/meta

GLOBAL_DEFAULT_IP=$META_PATH/default_ip
GLOBAL_HOST_IP=$META_PATH/host_ip

GLOBAL_DEFAULT_START_IP="10.200.1.1"
GLOBAL_HOST_START_IP="10.100.1.1"

MASK="16"
CONTAINER_MASK="24"

ROOTFS_ARCHIVE_PATH=$PROJECT_PATH/rootfs.tar

VIRTUAL_BRIDGE_NAME="pocbr0"